language: cpp
dist: xenial
sudo: required

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd ..
  - ./set_things_up.sh
  - ./download_videos.sh
  - ./run_basic_test.sh

before_script:
  - eval "${MATRIX_EVAL}"

before_install:
  ##### CMAKE #####
  - wget https://cmake.org/files/v3.12/cmake-3.12.2-Linux-x86_64.sh
  - sudo sh cmake-3.12.2-Linux-x86_64.sh --prefix=/home/travis/.local/ --exclude-subdir
  ##### FFMPEG #####
  - sudo add-apt-repository ppa:jonathonf/ffmpeg-4 -y
  - sudo apt-get update
  - sudo apt-get install ffmpeg
  ##### TCLAP #####
  - sudo apt-get install libtclap-dev
  ##### NGINX + NGINX DEPENDENCIES + RTMP MODULE + CONF FILE #####
  - sudo apt-get install libssl-dev
  - pushd .
  - mkdir ~/build-nginx && cd ~/build-nginx
  - git clone https://github.com/sergey-dryabzhinsky/nginx-rtmp-module.git
  - wget https://nginx.org/download/nginx-1.15.4.tar.gz
  - tar xzf nginx-1.15.4.tar.gz
  - cd nginx-1.15.4
  - ./configure --with-http_ssl_module --add-module=../nginx-rtmp-module
  - make -j 2
  - sudo make install
  - sudo cp ~/build/Zialus/SD-Video-Streaming/extras/nginx.conf /usr/local/nginx/conf/
  - sudo /usr/local/nginx/sbin/nginx
  - popd
  ##### ZERO ICE 3.7 #####
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv B6391CB2CFBA643D
  - sudo apt-add-repository "deb http://zeroc.com/download/Ice/3.7/ubuntu16.04 stable main"
  - sudo apt-get update
  - sudo apt-get install zeroc-ice-all-runtime zeroc-ice-all-dev


matrix:
  include:

    ######## LINUX GCC ########
    - os: linux
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - g++-4.9
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
    - os: linux
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - g++-5
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    - os: linux
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - os: linux
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

    ######## LINUX CLANG ########
    - os: linux
      addons:
        apt:
          sources:
            - sourceline: 'deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-3.9 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-3.9
      env:
        - MATRIX_EVAL="CC=clang-3.9 && CXX=clang++-3.9"
    - os: linux
      addons:
        apt:
          sources:
            - sourceline: 'deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-4.0 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-4.0
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"
    - os: linux
      addons:
        apt:
          sources:
            - sourceline: 'deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-5.0 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
    - os: linux
      addons:
        apt:
          sources:
            - sourceline: 'deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-6.0 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-6.0
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
    - os: linux
      addons:
        apt:
          sources:
            - sourceline: 'deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-7 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-7
      env:
        - MATRIX_EVAL="CC=clang-7 && CXX=clang++-7"


    ######## OSX CLANG ########
    - os: osx
      osx_image: xcode10
      env:
        - MATRIX_EVAL="CC=clang-3.9 && CXX=clang++"
      before_install: &mac_setup
        - brew update
        - brew install -v ffmpeg --with-x265
        - brew install tclap
        - brew install ice
        - brew tap denji/nginx
        - brew install nginx-full --with-rtmp-module
        - cp ~/build/Zialus/SD-Video-Streaming/extras/nginx.conf /usr/local/etc/nginx/
        - nginx
      install:
        - brew cask uninstall oclint && brew install llvm@3.9 && brew link --overwrite llvm@3.9 --force
    - os: osx
      osx_image: xcode10
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++"
      before_install: *mac_setup
      install:
        - brew cask uninstall oclint && brew install llvm@4 && brew link --overwrite llvm@4 --force
    - os: osx
      osx_image: xcode10
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++"
      before_install: *mac_setup
      install:
        - brew cask uninstall oclint && brew install llvm@5 && brew link --overwrite llvm@5 --force
    - os: osx
      osx_image: xcode10
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++"
      before_install: *mac_setup
      install:
        - brew cask uninstall oclint && brew install llvm@6 && brew link --overwrite llvm@6 --force
    - os: osx
      osx_image: xcode9.4
      env:
        - MATRIX_EVAL="CC=clang-7 && CXX=clang++"
      before_install: *mac_setup
      install:
        - brew cask uninstall oclint && brew install llvm@7 && brew link --overwrite llvm@7 --force

    ######## OSX GCC ########
    - os: osx
      osx_image: xcode10
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
      before_install: *mac_setup
      install:
        - brew cask uninstall oclint && brew install gcc@4.9
    - os: osx
      osx_image: xcode10
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
      before_install: *mac_setup
      install:
        - brew cask uninstall oclint && brew install gcc@5
    - os: osx
      osx_image: xcode10
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
      before_install: *mac_setup
      install:
        - brew cask uninstall oclint && brew install gcc@6
    - os: osx
      osx_image: xcode10
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      before_install: *mac_setup
      install:
        - brew cask uninstall oclint && brew install gcc@7
    - os: osx
      osx_image: xcode10
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
      before_install: *mac_setup
      install:
        - brew cask uninstall oclint && brew install gcc@8


  allow_failures:
    - env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
    - env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    - env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
