language: cpp
sudo: required
dist: trusty

script:
    - mkdir build && cd build
    - cmake .. && make
    - cd ..
    - ./download_videos.sh
    - ./set_things_up.sh
    - ./run_basic_test.sh

matrix:
  include:
    - os: linux
      compiler: g++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - COMPILER="g++-6"
        - EXTRALIBS="-L /usr/lib/x86_64-linux-gnu/c++11/"
      before_install:
        - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv 5E6DA83306132997
        - sudo apt-add-repository "deb http://zeroc.com/download/apt/ubuntu$(lsb_release -rs) stable main"
        - sudo add-apt-repository ppa:mc3man/trusty-media -y
        - sudo apt-get update -y
        - sudo apt-get install zeroc-ice-all-runtime zeroc-ice-all-dev ffmpeg
        - sudo apt-get install build-essential libpcre3 libpcre3-dev libssl-dev
        - sudo mkdir ~/build-nginx && cd ~/build-nginx
        - sudo git clone git://github.com/arut/nginx-rtmp-module.git
        - sudo wget http://nginx.org/download/nginx-1.10.2.tar.gz
        - sudo tar xzf nginx-1.10.2.tar.gz
        - cd nginx-1.10.2
        - sudo ./configure --with-http_ssl_module --add-module=../nginx-rtmp-module
        - sudo make
        - sudo make install
        - sudo /usr/local/nginx/sbin/nginx
        - cd ..
    - os: linux
      compiler: clang++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - COMPILER="clang++-3.9"
        - EXTRALIBS="-L /usr/lib/x86_64-linux-gnu/c++11/"
      before_install:
        - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv 5E6DA83306132997
        - sudo apt-add-repository "deb http://zeroc.com/download/apt/ubuntu$(lsb_release -rs) stable main"
        - wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        - sudo apt-add-repository "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main"
        - sudo add-apt-repository ppa:mc3man/trusty-media -y
        - sudo apt-get update -y
        - sudo apt-get install zeroc-ice-all-runtime zeroc-ice-all-dev clang-3.9 libc++-dev libc++abi-dev ffmpeg
        - sudo apt-get install build-essential libpcre3 libpcre3-dev libssl-dev
        - sudo mkdir ~/build-nginx && cd ~/build-nginx
        - sudo git clone git://github.com/arut/nginx-rtmp-module.git
        - sudo wget http://nginx.org/download/nginx-1.10.2.tar.gz
        - sudo tar xzf nginx-1.10.2.tar.gz
        - cd nginx-1.10.2
        - sudo ./configure --with-http_ssl_module --add-module=../nginx-rtmp-module
        - sudo make
        - sudo make install
        - sudo /usr/local/nginx/sbin/nginx
        - cd ..
    - os: osx
      osx_image: xcode8.2
      compiler: clang
      env: COMPILER=clang++
      before_install:
        - brew tap homebrew/nginx
        - brew update
        - brew install cmake
        - brew install ice
        - brew install ffmpeg
        - brew install nginx-full --with-rtmp-module
        - nginx