language: cpp
sudo: required
dist: trusty
os: osx
osx_image: xcode8.2

compiler:
  - clang
  - gcc


before_install:
    - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then brew update; fi
    - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then brew install ice; fi

script:
    make

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env: COMPILER=g++-6
      before_install:
        - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv 5E6DA83306132997
        - sudo apt-add-repository "deb http://zeroc.com/download/apt/ubuntu$(lsb_release -rs) stable main"
        - sudo apt-get update
        - sudo apt-get install zeroc-ice-all-runtime zeroc-ice-all-dev
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.8
          packages:
            - clang-3.8
      env: COMPILER=clang++-3.8
      before_install:
        - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv 5E6DA83306132997
        - sudo apt-add-repository "deb http://zeroc.com/download/apt/ubuntu$(lsb_release -rs) stable main"
        - sudo apt-get update
        - sudo apt-get install zeroc-ice-all-runtime zeroc-ice-all-dev
