language: cpp
dist: trusty
sudo: required

script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - cd ..
    - ./set_things_up.sh
    - ./download_videos.sh
    - ./run_basic_test.sh

before_script:
    - eval "${MATRIX_EVAL}"

before_install:
  ##### FFMPEG + TCLAP + READLINE + RANDOM STUFF FOR NGINX#####
  - sudo add-apt-repository ppa:jonathonf/ffmpeg-3 -y
  - sudo apt-get install ffmpeg libtclap-dev libreadline-dev
  - sudo apt-get install build-essential libpcre3 libpcre3-dev libssl-dev
  ##### ZERO ICE 3.7 #####
  - sudo sed -i 's/trusty/zesty/g' /etc/apt/sources.list
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv B6391CB2CFBA643D
  - sudo apt-add-repository "deb http://zeroc.com/download/Ice/3.7/ubuntu16.04 stable main"
  - sudo apt-get update -y
  - sudo apt-get install zeroc-ice-all-runtime zeroc-ice-all-dev
  ##### CMAKE 3.10 ######
  - wget https://cmake.org/files/v3.10/cmake-3.10.0-rc1-Linux-x86_64.sh
  - sudo sh cmake-3.10.0-rc1-Linux-x86_64.sh --prefix=/usr/local --exclude-subdir
  ##### NGINX + RTMP MODULE + CONF FILE #####
  - pushd .
  - sudo mkdir ~/build-nginx && cd ~/build-nginx
  - sudo wget https://github.com/arut/nginx-rtmp-module/archive/v1.2.0.tar.gz
  - sudo wget https://nginx.org/download/nginx-1.13.5.tar.gz
  - sudo tar xzvf nginx-1.13.5.tar.gz
  - sudo tar xzvf v1.2.0.tar.gz
  - cd nginx-1.13.5
  - sudo ./configure --with-http_ssl_module --add-module=../nginx-rtmp-module-1.2.0
  - sudo make
  - sudo make install
  - sudo cp ~/build/Zialus/SD-Video-Streaming/extras/nginx.conf /usr/local/nginx/conf/
  - sudo /usr/local/nginx/sbin/nginx
  - popd

matrix:
  include:

      ######## LINUX GCC ########
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    ######## LINUX CLANG ########
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-3.9
            - ubuntu-toolchain-r-test
          packages:
            - clang-3.9
            - libstdc++-6-dev
      env:
        - MATRIX_EVAL="CC=clang-3.9 && CXX=clang++-3.9"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"


    ######## OSX CLANG ########
    - os: osx
      osx_image: xcode9.1
      env:
        - MATRIX_EVAL="CC=clang-3.9 && CXX=clang++"
      before_install:
        - brew tap homebrew/nginx
        - brew update
        - brew install tclap
        - brew install ice
        - brew install -v ffmpeg --with-x265
        - brew install nginx-full --with-rtmp-module
        - brew cask uninstall oclint && brew install llvm@3.9 && brew link --overwrite llvm@3.9 --force
        - cp ~/build/Zialus/SD-Video-Streaming/extras/nginx.conf /usr/local/etc/nginx/
        - nginx
    - os: osx
      osx_image: xcode9.1
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++"
      before_install:
        - brew tap homebrew/nginx
        - brew update
        - brew install tclap
        - brew install ice
        - brew install -v ffmpeg --with-x265
        - brew install nginx-full --with-rtmp-module
        - brew cask uninstall oclint && brew install llvm@4 && brew link --overwrite llvm@4 --force
        - cp ~/build/Zialus/SD-Video-Streaming/extras/nginx.conf /usr/local/etc/nginx/
        - nginx
    - os: osx
      osx_image: xcode9.1
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++"
      before_install:
        - brew tap homebrew/nginx
        - brew update
        - brew install tclap
        - brew install ice
        - brew install -v ffmpeg --with-x265
        - brew install nginx-full --with-rtmp-module
        - brew cask uninstall oclint && brew install llvm && brew link --overwrite llvm --force
        - cp ~/build/Zialus/SD-Video-Streaming/extras/nginx.conf /usr/local/etc/nginx/
        - nginx