language: cpp
sudo: required
dist: trusty
os:
  - linux
  - osx

compiler:
  - clang
  - gcc

addons:
 apt:
  packages:
   - zeroc-ice-all-runtime
   - zeroc-ice-all-dev
before_install:
    osx:
        - brew update
        - brew install ice
    linux:
        - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv 5E6DA83306132997
        - sudo apt-add-repository "deb http://zeroc.com/download/apt/ubuntu$(lsb_release -rs) stable main"
        - sudo apt-get update
        - sudo apt-get install zeroc-ice-all-runtime zeroc-ice-all-dev

script:
    make
