language: cpp
sudo: required
dist: trusty

script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - cd ..
    - ./set_things_up.sh
    - ./download_videos.sh
    - ./run_basic_test.sh

before_script:
    - eval "${MATRIX_EVAL}"

matrix:
  include:

      ######## LINUX GCC ########
    - os: linux
      compiler: g++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      before_install:
        - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv 5E6DA83306132997
        - sudo apt-add-repository "deb http://zeroc.com/download/apt/ubuntu$(lsb_release -rs) stable main"
        - sudo add-apt-repository ppa:mc3man/trusty-media -y
        - sudo apt-get update -y
        - sudo apt-get install zeroc-ice-all-runtime zeroc-ice-all-dev ffmpeg libtclap-dev
        - sudo apt-get install build-essential libpcre3 libpcre3-dev libssl-dev
        - pushd .
        - sudo mkdir ~/build-nginx && cd ~/build-nginx
        - sudo git clone git://github.com/sergey-dryabzhinsky/nginx-rtmp-module.git
        - sudo wget http://nginx.org/download/nginx-1.10.3.tar.gz
        - sudo tar xzf nginx-1.10.3.tar.gz
        - cd nginx-1.10.3
        - sudo ./configure --with-http_ssl_module --add-module=../nginx-rtmp-module
        - sudo make
        - sudo make install
        - sudo cp ~/build/Zialus/SD-Video-Streaming/extras/nginx.conf /usr/local/nginx/conf/
        - sudo /usr/local/nginx/sbin/nginx
        - popd

    ######## LINUX CLANG ########
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"
      before_install:
        - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv 5E6DA83306132997
        - sudo apt-add-repository "deb http://zeroc.com/download/apt/ubuntu$(lsb_release -rs) stable main"
        - sudo add-apt-repository ppa:mc3man/trusty-media -y
        - sudo apt-get update -y
        - sudo apt-get install zeroc-ice-all-runtime zeroc-ice-all-dev ffmpeg libtclap-dev
        - sudo apt-get install build-essential libpcre3 libpcre3-dev libssl-dev
        - pushd .
        - sudo mkdir ~/build-nginx && cd ~/build-nginx
        - sudo git clone git://github.com/sergey-dryabzhinsky/nginx-rtmp-module.git
        - sudo wget http://nginx.org/download/nginx-1.10.3.tar.gz
        - sudo tar xzf nginx-1.10.3.tar.gz
        - cd nginx-1.10.3
        - sudo ./configure --with-http_ssl_module --add-module=../nginx-rtmp-module
        - sudo make
        - sudo make install
        - sudo cp ~/build/Zialus/SD-Video-Streaming/extras/nginx.conf /usr/local/nginx/conf/
        - sudo /usr/local/nginx/sbin/nginx
        - popd

    ######## OSX CLANG ########
    - os: osx
      osx_image: xcode9
      env:
        - MATRIX_EVAL="CC=clang-3.9 && CXX=clang++"
      before_install:
        - brew tap homebrew/nginx
        - brew update
        - brew install tclap
        - brew install ice
        - brew install -v ffmpeg --with-x265
        - brew install nginx-full --with-rtmp-module
        - brew cask uninstall oclint && brew install llvm@3.9 && brew link --overwrite llvm@3.9 --force
        - cp ~/build/Zialus/SD-Video-Streaming/extras/nginx.conf /usr/local/etc/nginx/
        - nginx
    - os: osx
      osx_image: xcode9
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++"
      before_install:
        - brew tap homebrew/nginx
        - brew update
        - brew install tclap
        - brew install ice
        - brew install -v ffmpeg --with-x265
        - brew install nginx-full --with-rtmp-module
        - brew cask uninstall oclint && brew install llvm && brew link --overwrite llvm --force
        - cp ~/build/Zialus/SD-Video-Streaming/extras/nginx.conf /usr/local/etc/nginx/
        - nginx
