language: cpp
sudo: required
dist: trusty

script:
    make

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env: COMPILER=g++-6
      before_install:
        - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv 5E6DA83306132997
        - sudo apt-add-repository "deb http://zeroc.com/download/apt/ubuntu$(lsb_release -rs) stable main"
        - sudo apt-get update
        - sudo apt-get install zeroc-ice-all-runtime zeroc-ice-all-dev
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env: COMPILER=clang++-3.9
      before_install:
        - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv 5E6DA83306132997
        - sudo apt-add-repository "deb http://zeroc.com/download/apt/ubuntu$(lsb_release -rs) stable main"
        - wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        - sudo apt-add-repository "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main"
        - sudo apt-get update
        - sudo apt-get install zeroc-ice-all-runtime zeroc-ice-all-dev clang-3.9
    - os: osx
      osx_image: xcode8.2
      compiler: gcc
      env: COMPILER=g++-6
      before_install:
        - brew update
        - brew install ice gcc
    - os: osx
      osx_image: xcode8.2
      compiler: clang
      env: COMPILER=clang++
      before_install:
        - brew update
        - brew unlink oclint
        - brew install ice
