language: cpp
sudo: required
dist: trusty

script:
    - mkdir build && cd build
    - cmake .. && make
    - cd ..
    - ./download_videos.sh
    - ./set_things_up.sh
    - ./run_basic_test.sh

matrix:
  include:
    - os: linux
      compiler: g++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - COMPILER="g++-6"
        - EXTRALIBS="-L /usr/lib/x86_64-linux-gnu/c++11/"
      before_install:
        - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv 5E6DA83306132997
        - sudo apt-add-repository "deb http://zeroc.com/download/apt/ubuntu$(lsb_release -rs) stable main"
        - sudo add-apt-repository ppa:mc3man/trusty-media -y
        - sudo apt-get update -y
        - sudo apt-get install zeroc-ice-all-runtime zeroc-ice-all-dev ffmpeg
    - os: linux
      compiler: clang++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - COMPILER="clang++-3.9"
        - EXTRALIBS="-L /usr/lib/x86_64-linux-gnu/c++11/"
      before_install:
        - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv 5E6DA83306132997
        - sudo apt-add-repository "deb http://zeroc.com/download/apt/ubuntu$(lsb_release -rs) stable main"
        - wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        - sudo apt-add-repository "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main"
        - sudo add-apt-repository ppa:mc3man/trusty-media -y
        - sudo apt-get update -y
        - sudo apt-get install zeroc-ice-all-runtime zeroc-ice-all-dev clang-3.9 libc++-dev libc++abi-dev ffmpeg
    - os: osx
      osx_image: xcode8.2
      compiler: clang
      env: COMPILER=clang++
      before_install:
        - brew update
        - brew install cmake
        - brew install ice
        - brew install ffmpeg
