language: cpp
sudo: required
dist: trusty
os:
  - linux
  - osx

compiler:
  - clang
  - gcc


before_install:
    osx:
        - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then brew update; fi
        - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then brew install ice; fi
    linux:
        - if [ "${TRAVIS_OS_NAME}" == "linux" ]; sudo apt-key adv --keyserver keyserver.ubuntu.com --recv 5E6DA83306132997; fi
        - if [ "${TRAVIS_OS_NAME}" == "linux" ]; sudo apt-add-repository "deb http://zeroc.com/download/apt/ubuntu$(lsb_release -rs) stable main"; fi
        - if [ "${TRAVIS_OS_NAME}" == "linux" ]; sudo apt-get update; fi
        - if [ "${TRAVIS_OS_NAME}" == "linux" ]; sudo apt-get install zeroc-ice-all-runtime zeroc-ice-all-dev; fi

script:
    make
